### ISSUE TITLE
Mod request: change white marble floor to grey

### ISSUE THREAD

**Issue by TragicallyNewb** [viniotstudios/pickleball_issues#5]
- [ ] SETTINGS ACTIVE: left hand, teleport, chair mode
- [ ] GAME MODE: Various
- [ ] CONDITION: White marble floor makes the ball difficult to see
- [ ] POSSIBLE SOLUTION: Darken the floor a bit? Perhaps a shade of grey would improve the ball's visibility.

**Comment by viniotstudios** [comment]
Excellent suggestion! Will do.

**Comment by viniotstudios** [comment]
Changed the color to blue gray in 1.0.3
